/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminInfoRouteImport } from './routes/admin.info'
import { Route as AdminLicenseRouteImport } from './routes/admin.license'
import { Route as AdminLocksRouteImport } from './routes/admin.locks'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as ApiCreateMemberRouteImport } from './routes/api/create-member'
import { Route as ApiGeneratePosterRouteImport } from './routes/api/generate-poster'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppInfoRouteImport } from './routes/app.info'
import { Route as AppKasirRouteImport } from './routes/app.kasir'
import { Route as AppModalRouteImport } from './routes/app.modal'
import { Route as AppPemasaranRouteImport } from './routes/app.pemasaran'
import { Route as AppPengaturanRouteImport } from './routes/app.pengaturan'
import { Route as AppStokRouteImport } from './routes/app.stok'
import { Route as ApiPublicLynkWebhookRouteImport } from './routes/api/public/lynk-webhook'
import { Route as ApiPublicResetPasswordRouteImport } from './routes/api/public/reset-password'
import { Route as AppKasirIndexRouteImport } from './routes/app.kasir.index'
import { Route as AppKasirAiRouteImport } from './routes/app.kasir.ai'
import { Route as AppKasirKasRouteImport } from './routes/app.kasir.kas'
import { Route as AppKasirManajemenRouteImport } from './routes/app.kasir.manajemen'
import { Route as AppKasirPosRouteImport } from './routes/app.kasir.pos'
import { Route as AppKasirRekapRouteImport } from './routes/app.kasir.rekap'
import { Route as AppKasirRiwayatRouteImport } from './routes/app.kasir.riwayat'
import { Route as AppKasirStrukRouteImport } from './routes/app.kasir.struk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfoRoute = AdminInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicenseRoute = AdminLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocksRoute = AdminLocksRouteImport.update({
  id: '/locks',
  path: '/locks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCreateMemberRoute = ApiCreateMemberRouteImport.update({
  id: '/api/create-member',
  path: '/api/create-member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePosterRoute = ApiGeneratePosterRouteImport.update({
  id: '/api/generate-poster',
  path: '/api/generate-poster',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInfoRoute = AppInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AppRoute,
} as any)
const AppKasirRoute = AppKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AppRoute,
} as any)
const AppModalRoute = AppModalRouteImport.update({
  id: '/modal',
  path: '/modal',
  getParentRoute: () => AppRoute,
} as any)
const AppPemasaranRoute = AppPemasaranRouteImport.update({
  id: '/pemasaran',
  path: '/pemasaran',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppStokRoute = AppStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicLynkWebhookRoute = ApiPublicLynkWebhookRouteImport.update({
  id: '/api/public/lynk-webhook',
  path: '/api/public/lynk-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResetPasswordRoute = ApiPublicResetPasswordRouteImport.update({
  id: '/api/public/reset-password',
  path: '/api/public/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKasirIndexRoute = AppKasirIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKasirRoute,
} as any)
const AppKasirAiRoute = AppKasirAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppKasirRoute,
} as any)
const AppKasirKasRoute = AppKasirKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AppKasirRoute,
} as any)
const AppKasirManajemenRoute = AppKasirManajemenRouteImport.update({
  id: '/manajemen',
  path: '/manajemen',
  getParentRoute: () => AppKasirRoute,
} as any)
const AppKasirPosRoute = AppKasirPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppKasirRoute,
} as any)
const AppKasirRekapRoute = AppKasirRekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => AppKasirRoute,
} as any)
const AppKasirRiwayatRoute = AppKasirRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AppKasirRoute,
} as any)
const AppKasirStrukRoute = AppKasirStrukRouteImport.update({
  id: '/struk',
  path: '/struk',
  getParentRoute: () => AppKasirRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/info': typeof AdminInfoRoute
  '/admin/license': typeof AdminLicenseRoute
  '/admin/locks': typeof AdminLocksRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/api/create-member': typeof ApiCreateMemberRoute
  '/api/generate-poster': typeof ApiGeneratePosterRoute
  '/app/info': typeof AppInfoRoute
  '/app/kasir': typeof AppKasirRouteWithChildren
  '/app/modal': typeof AppModalRoute
  '/app/pemasaran': typeof AppPemasaranRoute
  '/app/pengaturan': typeof AppPengaturanRoute
  '/app/stok': typeof AppStokRoute
  '/app/': typeof AppIndexRoute
  '/api/public/lynk-webhook': typeof ApiPublicLynkWebhookRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
  '/app/kasir/ai': typeof AppKasirAiRoute
  '/app/kasir/kas': typeof AppKasirKasRoute
  '/app/kasir/manajemen': typeof AppKasirManajemenRoute
  '/app/kasir/pos': typeof AppKasirPosRoute
  '/app/kasir/rekap': typeof AppKasirRekapRoute
  '/app/kasir/riwayat': typeof AppKasirRiwayatRoute
  '/app/kasir/struk': typeof AppKasirStrukRoute
  '/app/kasir/': typeof AppKasirIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/info': typeof AdminInfoRoute
  '/admin/license': typeof AdminLicenseRoute
  '/admin/locks': typeof AdminLocksRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/api/create-member': typeof ApiCreateMemberRoute
  '/api/generate-poster': typeof ApiGeneratePosterRoute
  '/app/info': typeof AppInfoRoute
  '/app/modal': typeof AppModalRoute
  '/app/pemasaran': typeof AppPemasaranRoute
  '/app/pengaturan': typeof AppPengaturanRoute
  '/app/stok': typeof AppStokRoute
  '/app': typeof AppIndexRoute
  '/api/public/lynk-webhook': typeof ApiPublicLynkWebhookRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
  '/app/kasir/ai': typeof AppKasirAiRoute
  '/app/kasir/kas': typeof AppKasirKasRoute
  '/app/kasir/manajemen': typeof AppKasirManajemenRoute
  '/app/kasir/pos': typeof AppKasirPosRoute
  '/app/kasir/rekap': typeof AppKasirRekapRoute
  '/app/kasir/riwayat': typeof AppKasirRiwayatRoute
  '/app/kasir/struk': typeof AppKasirStrukRoute
  '/app/kasir': typeof AppKasirIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/info': typeof AdminInfoRoute
  '/admin/license': typeof AdminLicenseRoute
  '/admin/locks': typeof AdminLocksRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/api/create-member': typeof ApiCreateMemberRoute
  '/api/generate-poster': typeof ApiGeneratePosterRoute
  '/app/info': typeof AppInfoRoute
  '/app/kasir': typeof AppKasirRouteWithChildren
  '/app/modal': typeof AppModalRoute
  '/app/pemasaran': typeof AppPemasaranRoute
  '/app/pengaturan': typeof AppPengaturanRoute
  '/app/stok': typeof AppStokRoute
  '/app/': typeof AppIndexRoute
  '/api/public/lynk-webhook': typeof ApiPublicLynkWebhookRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
  '/app/kasir/ai': typeof AppKasirAiRoute
  '/app/kasir/kas': typeof AppKasirKasRoute
  '/app/kasir/manajemen': typeof AppKasirManajemenRoute
  '/app/kasir/pos': typeof AppKasirPosRoute
  '/app/kasir/rekap': typeof AppKasirRekapRoute
  '/app/kasir/riwayat': typeof AppKasirRiwayatRoute
  '/app/kasir/struk': typeof AppKasirStrukRoute
  '/app/kasir/': typeof AppKasirIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/ai'
    | '/admin/info'
    | '/admin/license'
    | '/admin/locks'
    | '/admin/tenants'
    | '/api/create-member'
    | '/api/generate-poster'
    | '/app/info'
    | '/app/kasir'
    | '/app/modal'
    | '/app/pemasaran'
    | '/app/pengaturan'
    | '/app/stok'
    | '/app/'
    | '/api/public/lynk-webhook'
    | '/api/public/reset-password'
    | '/app/kasir/ai'
    | '/app/kasir/kas'
    | '/app/kasir/manajemen'
    | '/app/kasir/pos'
    | '/app/kasir/rekap'
    | '/app/kasir/riwayat'
    | '/app/kasir/struk'
    | '/app/kasir/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/ai'
    | '/admin/info'
    | '/admin/license'
    | '/admin/locks'
    | '/admin/tenants'
    | '/api/create-member'
    | '/api/generate-poster'
    | '/app/info'
    | '/app/modal'
    | '/app/pemasaran'
    | '/app/pengaturan'
    | '/app/stok'
    | '/app'
    | '/api/public/lynk-webhook'
    | '/api/public/reset-password'
    | '/app/kasir/ai'
    | '/app/kasir/kas'
    | '/app/kasir/manajemen'
    | '/app/kasir/pos'
    | '/app/kasir/rekap'
    | '/app/kasir/riwayat'
    | '/app/kasir/struk'
    | '/app/kasir'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/ai'
    | '/admin/info'
    | '/admin/license'
    | '/admin/locks'
    | '/admin/tenants'
    | '/api/create-member'
    | '/api/generate-poster'
    | '/app/info'
    | '/app/kasir'
    | '/app/modal'
    | '/app/pemasaran'
    | '/app/pengaturan'
    | '/app/stok'
    | '/app/'
    | '/api/public/lynk-webhook'
    | '/api/public/reset-password'
    | '/app/kasir/ai'
    | '/app/kasir/kas'
    | '/app/kasir/manajemen'
    | '/app/kasir/pos'
    | '/app/kasir/rekap'
    | '/app/kasir/riwayat'
    | '/app/kasir/struk'
    | '/app/kasir/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ApiCreateMemberRoute: typeof ApiCreateMemberRoute
  ApiGeneratePosterRoute: typeof ApiGeneratePosterRoute
  ApiPublicLynkWebhookRoute: typeof ApiPublicLynkWebhookRoute
  ApiPublicResetPasswordRoute: typeof ApiPublicResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/info': {
      id: '/admin/info'
      path: '/info'
      fullPath: '/admin/info'
      preLoaderRoute: typeof AdminInfoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/license': {
      id: '/admin/license'
      path: '/license'
      fullPath: '/admin/license'
      preLoaderRoute: typeof AdminLicenseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locks': {
      id: '/admin/locks'
      path: '/locks'
      fullPath: '/admin/locks'
      preLoaderRoute: typeof AdminLocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/create-member': {
      id: '/api/create-member'
      path: '/api/create-member'
      fullPath: '/api/create-member'
      preLoaderRoute: typeof ApiCreateMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-poster': {
      id: '/api/generate-poster'
      path: '/api/generate-poster'
      fullPath: '/api/generate-poster'
      preLoaderRoute: typeof ApiGeneratePosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/info': {
      id: '/app/info'
      path: '/info'
      fullPath: '/app/info'
      preLoaderRoute: typeof AppInfoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kasir': {
      id: '/app/kasir'
      path: '/kasir'
      fullPath: '/app/kasir'
      preLoaderRoute: typeof AppKasirRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/modal': {
      id: '/app/modal'
      path: '/modal'
      fullPath: '/app/modal'
      preLoaderRoute: typeof AppModalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pemasaran': {
      id: '/app/pemasaran'
      path: '/pemasaran'
      fullPath: '/app/pemasaran'
      preLoaderRoute: typeof AppPemasaranRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pengaturan': {
      id: '/app/pengaturan'
      path: '/pengaturan'
      fullPath: '/app/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stok': {
      id: '/app/stok'
      path: '/stok'
      fullPath: '/app/stok'
      preLoaderRoute: typeof AppStokRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/lynk-webhook': {
      id: '/api/public/lynk-webhook'
      path: '/api/public/lynk-webhook'
      fullPath: '/api/public/lynk-webhook'
      preLoaderRoute: typeof ApiPublicLynkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reset-password': {
      id: '/api/public/reset-password'
      path: '/api/public/reset-password'
      fullPath: '/api/public/reset-password'
      preLoaderRoute: typeof ApiPublicResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/kasir/': {
      id: '/app/kasir/'
      path: '/'
      fullPath: '/app/kasir/'
      preLoaderRoute: typeof AppKasirIndexRouteImport
      parentRoute: typeof AppKasirRoute
    }
    '/app/kasir/ai': {
      id: '/app/kasir/ai'
      path: '/ai'
      fullPath: '/app/kasir/ai'
      preLoaderRoute: typeof AppKasirAiRouteImport
      parentRoute: typeof AppKasirRoute
    }
    '/app/kasir/kas': {
      id: '/app/kasir/kas'
      path: '/kas'
      fullPath: '/app/kasir/kas'
      preLoaderRoute: typeof AppKasirKasRouteImport
      parentRoute: typeof AppKasirRoute
    }
    '/app/kasir/manajemen': {
      id: '/app/kasir/manajemen'
      path: '/manajemen'
      fullPath: '/app/kasir/manajemen'
      preLoaderRoute: typeof AppKasirManajemenRouteImport
      parentRoute: typeof AppKasirRoute
    }
    '/app/kasir/pos': {
      id: '/app/kasir/pos'
      path: '/pos'
      fullPath: '/app/kasir/pos'
      preLoaderRoute: typeof AppKasirPosRouteImport
      parentRoute: typeof AppKasirRoute
    }
    '/app/kasir/rekap': {
      id: '/app/kasir/rekap'
      path: '/rekap'
      fullPath: '/app/kasir/rekap'
      preLoaderRoute: typeof AppKasirRekapRouteImport
      parentRoute: typeof AppKasirRoute
    }
    '/app/kasir/riwayat': {
      id: '/app/kasir/riwayat'
      path: '/riwayat'
      fullPath: '/app/kasir/riwayat'
      preLoaderRoute: typeof AppKasirRiwayatRouteImport
      parentRoute: typeof AppKasirRoute
    }
    '/app/kasir/struk': {
      id: '/app/kasir/struk'
      path: '/struk'
      fullPath: '/app/kasir/struk'
      preLoaderRoute: typeof AppKasirStrukRouteImport
      parentRoute: typeof AppKasirRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminInfoRoute: typeof AdminInfoRoute
  AdminLicenseRoute: typeof AdminLicenseRoute
  AdminLocksRoute: typeof AdminLocksRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminInfoRoute: AdminInfoRoute,
  AdminLicenseRoute: AdminLicenseRoute,
  AdminLocksRoute: AdminLocksRoute,
  AdminTenantsRoute: AdminTenantsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppKasirRouteChildren {
  AppKasirAiRoute: typeof AppKasirAiRoute
  AppKasirKasRoute: typeof AppKasirKasRoute
  AppKasirManajemenRoute: typeof AppKasirManajemenRoute
  AppKasirPosRoute: typeof AppKasirPosRoute
  AppKasirRekapRoute: typeof AppKasirRekapRoute
  AppKasirRiwayatRoute: typeof AppKasirRiwayatRoute
  AppKasirStrukRoute: typeof AppKasirStrukRoute
  AppKasirIndexRoute: typeof AppKasirIndexRoute
}

const AppKasirRouteChildren: AppKasirRouteChildren = {
  AppKasirAiRoute: AppKasirAiRoute,
  AppKasirKasRoute: AppKasirKasRoute,
  AppKasirManajemenRoute: AppKasirManajemenRoute,
  AppKasirPosRoute: AppKasirPosRoute,
  AppKasirRekapRoute: AppKasirRekapRoute,
  AppKasirRiwayatRoute: AppKasirRiwayatRoute,
  AppKasirStrukRoute: AppKasirStrukRoute,
  AppKasirIndexRoute: AppKasirIndexRoute,
}

const AppKasirRouteWithChildren = AppKasirRoute._addFileChildren(
  AppKasirRouteChildren,
)

interface AppRouteChildren {
  AppInfoRoute: typeof AppInfoRoute
  AppKasirRoute: typeof AppKasirRouteWithChildren
  AppModalRoute: typeof AppModalRoute
  AppPemasaranRoute: typeof AppPemasaranRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppStokRoute: typeof AppStokRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInfoRoute: AppInfoRoute,
  AppKasirRoute: AppKasirRouteWithChildren,
  AppModalRoute: AppModalRoute,
  AppPemasaranRoute: AppPemasaranRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppStokRoute: AppStokRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApiCreateMemberRoute: ApiCreateMemberRoute,
  ApiGeneratePosterRoute: ApiGeneratePosterRoute,
  ApiPublicLynkWebhookRoute: ApiPublicLynkWebhookRoute,
  ApiPublicResetPasswordRoute: ApiPublicResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
